#stanシンタックス
[[plugins]]
repo = 'maverickg/stan.vim'
on_ft = 'stan'

# カーソル位置のコンテキストに合わせてftを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = 'toml'

# カーソル位置のコンテキストのftを判定するライブラリ
[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_ft = 'toml'

#vimでR
[[plugins]]
repo = 'jalvesaq/Nvim-R'
if = '''!has('gui_running')'''
on_ft = 'r'
hook_add = '''
source ~/.config/nvim/plugins/Nvim-R.rc.vim
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
on_event = 'BufRead'
hook_post_update = '''
TSUpdate
'''
hook_source = '''
source ~/.config/nvim/plugins/nvim-treesitter.rc.lua
'''

# ステータスバーの装飾
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
on_event = 'BufRead'
hook_source = '''
source ~/.config/nvim/plugins/lualine.rc.lua
'''

