#vimプラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

# #ファイルツリー
# [[plugins]]
# repo = 'kyazdani42/nvim-tree.lua'
# hook_add = '''
# source ~/.config/nvim/plugins/nvim-tree.rc.lua
# '''

# file tree
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = """
source ~/.config/nvim/plugins/defx.rc.vim
"""

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

# tablineの装飾
[[plugins]]
repo = 'romgrk/barbar.nvim'
hook_add = '''
source ~/.config/nvim/plugins/barbar.rc.lua
'''

# アイコンの設定
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

#移動効率化
[[plugins]]
repo = 'easymotion/vim-easymotion'

#テンプレート
[[plugins]]
repo = 'mattn/sonictemplate-vim'

#インデント
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
source ~/.config/nvim/plugins/indentLine.rc.lua
'''

# #末尾の全角と半角の空白文字を赤色でハイライト
# [[plugins]]
# repo = 'bronson/vim-trailing-whitespace'

#コメントアウトon/off
[[plugins]]
repo = 'tomtom/tcomment_vim'

#vimからgit
[[plugins]]
repo = 'tpope/vim-fugitive'

# 差分を自動表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.config/nvim/plugins/vim-gitgutter.rc.lua
'''

# 対となる括弧を追加/削除する
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# completion
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.rc.lua
'''

# colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'EdenEast/nightfox.nvim'
[[plugins]]
repo = 'arcticicestudio/nord-vim'

# fuzzy finder
[[plugins]]
repo = 'nvim-lua/popup.nvim'
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = """
source ~/.config/nvim/plugins/telescope.rc.lua
"""
[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'

# vimのウィンドウサイズの変更
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
source ~/.config/nvim/plugins/winresizer.rc.lua
'''

