#vimでR
[[plugins]]
repo = 'jalvesaq/Nvim-R'
if = '''!has('gui_running')'''
on_ft = 'r'
hook_add = '''
source ~/.config/nvim/plugins/Nvim-R.rc.vim
'''

#stanシンタックス
[[plugins]]
repo = 'maverickg/stan.vim'
on_ft = 'stan'

# treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
on_event = 'BufRead'
hook_post_update = '''
TSUpdate
'''
hook_source = '''
source ~/.config/nvim/plugins/nvim-treesitter.rc.lua
'''

# ステータスバーの装飾
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
on_event = 'BufRead'
hook_source = '''
source ~/.config/nvim/plugins/lualine.rc.lua
'''

