add_newline = true
format = """
[┌─ ](bold green)$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$container\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$status\
$shell\
[└](bold green)$character"""

[username]
style_user = "white bold"
style_root = "green bold"
format = "user: [$user]($style) "
disabled = false

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"
read_only = " "
read_only_style = "red"

[git_branch]
symbol = " "
style = "#a093c7"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "red"

[python]
symbol = " "
style = "yellow"
pyenv_prefix = "pyenv "
pyenv_version_name = true

[rlang]
symbol = "ﳒ "
style = "blue"
detect_extensions = ["R", "Rd", "Rmd", "Rproj", "Rsx"]
detect_files = []

[lua]
symbol = " "
style = "#EBCB8B"

[nodejs]
style = 'green'

[julia]
symbol = " "
style = "#a093c7"

[ruby]
symbol = " "
style = "red"

[rust]
symbol = " "
style = "red"

[golang]
symbol = ' '

[package]
symbol = " "
style = "208"
