#tomlシンタックス
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

#stanシンタックス
[[plugins]]
repo = 'maverickg/stan.vim'
on_ft = 'stan'

# カーソル位置のコンテキストに合わせてftを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = 'toml'

# カーソル位置のコンテキストのftを判定するライブラリ
[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_ft = 'toml'

#vimでR
[[plugins]]
repo = 'jalvesaq/Nvim-R'
if = '''!has('gui_running')'''
on_ft = 'r'

#for tex
# [[plugins]]
# repo = 'lervag/vimtex'
# on_ft = 'tex'

