#tomlシンタックス
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

#stanシンタックス
[[plugins]]
repo = 'maverickg/stan.vim'
on_ft = 'stan'

# カーソル位置のコンテキストに合わせてftを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = 'toml'

# カーソル位置のコンテキストのftを判定するライブラリ
[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_ft = 'toml'

#vimでR
[[plugins]]
repo = 'jalvesaq/Nvim-R'
if = '''!has('gui_running')'''
on_ft = 'r'

#for tex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'

# fish syntax
[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

# indent for python
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

# コード補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_post_source = '''
let g:deoplete#omni_patterns = {}
'''
# hook_source = '''
# call deoplete#custom#option('auto_complete', v:false)
# inoremap <silent><expr> <C-p>
#     \ pumvisible() ? "\<C-p>" : deoplete#manual_complete()
# '''
hook_add = '''
  let g:deoplete#enable_at_startup   = 1
  let g:deoplete#max_list = 20
  let g:deoplete#auto_complete_delay = 0
  " let g:deoplete#enable_ignore_case = 1
  " let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  " let g:deoplete#enable_ignore_case = 0
  " let g:deoplete#enable_refresh_always = 0
  " let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
'''

# pythonコード補完用
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'
hook_add = '''
" jedi本体の補完は切る（deoplete-jediで非同期処理をしてくれるため）
let g:jedi#completions_enabled = 0
let g:deoplete#sources#jedi#show_docstring = 0
'''
