[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'nnoremap <silent><C-e> :NERDTreeToggle<CR>'

#stanシンタックス
[[plugins]]
repo = 'maverickg/stan.vim'

#自動鉤括弧閉める
[[plugins]]
repo = 'Townk/vim-autoclose'

#検索
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
nmap n <Plug>(anzu-n)
nmap N <Plug>(anzu-N)
nmap * <Plug>(anzu-star)
nmap # <Plug>(anzu-sharp)
nmap <Esc><Esc> <Plug>(anzu-clear-search-status)
augroup vim-anzu
autocmd!
    autocmd CursorHold,CursorHoldI,WinLeave,TabLeave * call anzu#clear_search_status()
augroup END
'''

# hybrid
[[plugins]]
repo = 'w0ng/vim-hybrid'

#lightlineカラースキーム
[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

#lightline各種設定
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
	\'active': {
	\	'left':  [ ['mode', 'paste'], ['readonly', 'fugitive', 'relativepath', 'modified', 'anzu'] ],
	\	'right': [ [ 'lineinfo'],
	\              [ 'percent' ],
	\              [ 'fileformat', 'fileencoding', 'filetype' ] ]
	\},
	\'component': {
	\ 'relativepath':'%F',
	\	'lineinfo': '⭡ %3l:%-2v',
	\	'readonly': '%{&readonly?"⭤":""}',
	\},
	\ 'component_function': {
	\	'fugitive': 'LightLineFugitive',
	\	'mode': 'LightLineMode',
	\	'modified': 'LightLineModified',
	\	'anzu': 'anzu#search_status'
	\}
	\}

function! LightLineModified()
  return &ft =~ 'help' ? '' : &modified ? '+' : &modifiable ? '' : '-'
endfunction

function! LightLineFugitive()
  if exists("*fugitive#head")
    let _ = fugitive#head()
    return strlen(_) ? '⭠ '._ : ''
  endif
  return ''
endfunction

function! LightLineMode()
  let fname = expand('%:t')
  return fname =~ 'NERD_tree' ? 'NERDTree' :
        \ winwidth(0) > 60 ? lightline#mode() : ''
endfunction

let g:lightline.colorscheme = 'hybrid'
'''

#クイックラン
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   'tex': {
\       'command': 'latexmk',
\       'exec': ['%c -gg -pdfdvi %s', 'open %s:r.pdf']
\   },
\}
'''

#移動効率化
[[plugins]]
repo = 'easymotion/vim-easymotion'

#テンプレート
[[plugins]]
repo = 'mattn/sonictemplate-vim'

# #vimにpyenv環境を適用
# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'
# depends = ['davidhalter/jedi-vim']
# on_ft = 'python'

#末尾の全角と半角の空白文字を赤色でハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

