#vimプラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

#ファイルツリー
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'nnoremap <silent><C-e> :NERDTreeToggle<CR>'

#自動鉤括弧閉める
[[plugins]]
repo = 'Townk/vim-autoclose'

#検索
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
nmap n <Plug>(anzu-n)
nmap N <Plug>(anzu-N)
nmap * <Plug>(anzu-star)
nmap # <Plug>(anzu-sharp)
nmap <Esc><Esc> <Plug>(anzu-clear-search-status)
augroup vim-anzu
autocmd!
    autocmd CursorHold,CursorHoldI,WinLeave,TabLeave * call anzu#clear_search_status()
augroup END
'''



[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#show_close_button = 0 " remove 'X' at the end of the tabline
let g:airline#extensions#tabline#tabs_label = ''       " can put text here like BUFFERS to denote buffers (I clear it so nothing is shown)
let g:airline#extensions#tabline#buffers_label = ''
let g:airline_theme = 'bubblegum'

set laststatus=2
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo = 'ryanoasis/vim-devicons'

#クイックラン
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   'tex': {
\       'command': 'latexmk',
\       'exec': ['%c -gg -pdfdvi %s', 'open %s:r.pdf']
\   },
\}
'''

#移動効率化
[[plugins]]
repo = 'easymotion/vim-easymotion'

#テンプレート
[[plugins]]
repo = 'mattn/sonictemplate-vim'

#インデント
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_setColors = 1
let g:indentLine_color_term = 243
let g:indentLine_char = '|'
'''
#末尾の全角と半角の空白文字を赤色でハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

#コメントアウトon/off
[[plugins]]
repo = 'tomtom/tcomment_vim'

#vimからgit
[[plugins]]
repo = 'tpope/vim-fugitive'

# 差分を自動表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# ctagsの作成
[[plugins]]
repo = 'szw/vim-tags'

# ctagsの一覧を表示
[[plugins]]
repo = 'majutsushi/tagbar'
