# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# # file tree
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
    let g:fern#default_hidden=1
    nnoremap <silent> sf :<C-u>Fern . -reveal=%<CR>
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
    let g:fern#renderer = "nerdfont"
'''
depends = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''
depends = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
depends = ['fern.vim']

# decorate tabline
[[plugins]]
repo = 'romgrk/barbar.nvim'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/barbar.rc.lua
'''

# icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# Move efficiently
[[plugins]]
repo = 'phaazon/hop.nvim'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/hop.rc.lua
'''

# template
[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/indent-blankline.rc.lua
'''

# comment on/off
[[plugins]]
repo = 'tomtom/tcomment_vim'

# git on vim
[[plugins]]
repo = 'tpope/vim-fugitive'

# code diff on left edge
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/vim-gitgutter.rc.lua
'''

# 対となる括弧を追加/削除する
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# completion
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/coc.rc.lua
'''

# colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'EdenEast/nightfox.nvim'
[[plugins]]
repo = 'arcticicestudio/nord-vim'
[[plugins]]
repo = 'folke/tokyonight.nvim'

# fuzzy finder
[[plugins]]
repo = 'nvim-lua/popup.nvim'
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = """
source ~/dotfiles/.config/nvim/plugins/telescope.rc.lua
"""
[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
[[plugins]]
repo = 'folke/todo-comments.nvim'
hook_add = """
source ~/dotfiles/.config/nvim/plugins/todo-comments.rc.lua
"""

# change window size of vim
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/winresizer.rc.lua
'''

# [[plugins]]
# repo = 'sunjon/Shade.nvim'
# hook_add = '''
# source ~/dotfiles/.config/nvim/plugins/shade.rc.lua
# '''

[[plugins]]
repo = 'eigenfoo/stan-vim'
