# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

# # file tree
# [[plugins]]
# repo = 'Shougo/defx.nvim'
# depends = ['defx-git', 'defx-icons']
# hook_add = """
# source ~/dotfiles/.config/nvim/plugins/defx.rc.vim
# """
#
# [[plugins]]
# repo = 'kristijanhusak/defx-icons'
#
# [[plugins]]
# repo = 'kristijanhusak/defx-git'

# decorate tabline
[[plugins]]
repo = 'romgrk/barbar.nvim'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/barbar.rc.lua
'''

# icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# Move efficiently
[[plugins]]
repo = 'phaazon/hop.nvim'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/hop.rc.lua
'''

# template
[[plugins]]
repo = 'mattn/sonictemplate-vim'

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/indent-blankline.rc.lua
'''

# comment on/off
[[plugins]]
repo = 'tomtom/tcomment_vim'

# git on vim
[[plugins]]
repo = 'tpope/vim-fugitive'

# code diff on left edge
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/vim-gitgutter.rc.lua
'''

# 対となる括弧を追加/削除する
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# completion
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/coc.rc.lua
'''

# colorscheme
[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'EdenEast/nightfox.nvim'
[[plugins]]
repo = 'arcticicestudio/nord-vim'

# fuzzy finder
[[plugins]]
repo = 'nvim-lua/popup.nvim'
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = """
source ~/dotfiles/.config/nvim/plugins/telescope.rc.lua
"""
[[plugins]]
repo = 'nvim-telescope/telescope-file-browser.nvim'
[[plugins]]
repo = 'folke/todo-comments.nvim'
hook_add = """
source ~/dotfiles/.config/nvim/plugins/todo-comments.rc.lua
"""

# change window size of vim
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
source ~/dotfiles/.config/nvim/plugins/winresizer.rc.lua
'''

# [[plugins]]
# repo = 'sunjon/Shade.nvim'
# hook_add = '''
# source ~/dotfiles/.config/nvim/plugins/shade.rc.lua
# '''

