# treesitter
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
on_event = 'BufRead'
hook_post_update = '''
TSUpdate
'''
hook_source = '''
source ~/dotfiles/.config/nvim/plugins/nvim-treesitter.rc.lua
'''

# To show the function under the cursor
[[plugins]]
repo = 'SmiteshP/nvim-gps'
on_event = 'BufRead'
hook_source = '''
source ~/dotfiles/.config/nvim/plugins/nvim-gps.rc.lua
'''

# ステータスバーの装飾
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
on_event = 'BufRead'
hook_source = '''
source ~/dotfiles/.config/nvim/plugins/lualine.rc.lua
'''

#vimでR
[[plugins]]
repo = 'jalvesaq/Nvim-R'
if = '''!has('gui_running')'''
on_ft = 'r'
